{{- if .Values.velero.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: default-backup
spec:
  schedule: {{ .Values.velero.schedule }}
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    storageLocation: ""
    ttl: {{ .Values.velero.ttl }}
    volumeSnapshotLocations: null
{{- end }}
