apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "{{ .Values.gitops.staging.owner | default .Values.gitops.owner }}-{{ .Values.gitops.staging.repo }}"
spec:
  provider: "{{ .Values.gitops.staging.server | default .Values.gitops.server }}"
  providerName: '{{ .Values.gitops.gitKind | default "github" }}'
  org: "{{ .Values.gitops.staging.owner | default .Values.gitops.owner }}"
  repo: "{{ .Values.gitops.staging.repo }}"
  description: "the git repository for the Staging environment"
  scheduler:
    kind: Scheduler
    name: env-scheduler