dependencies:
- name: jxboot-resources
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.1.27
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
  condition: jx-app-kuberhealthy.enabled
  alias: jx-app-kuberhealthy
- name: jx-repository-controller
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  condition: repositorycontroller.enabled
  alias: repositorycontroller
- name: jx-segment-controller
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.13
  condition: jx-segment-controller.enabled
  alias: jx-segment-controller
- name: jx-tenant-service
  alias: refresh
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  condition: refresh.enabled
- name: jx-arcalos-role-controller
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.6
  condition: jx-arcalos-role-controller.enabled
  alias: arcalosrole

