dependencies:
- name: jxboot-resources
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
# - name: "sso-operator"
#   repository: "https://storage.googleapis.com/chartmuseum.jenkins-x.io"
#   version: "1.2.33"
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
  condition: jx-app-kuberhealthy.enabled
  alias: jx-app-kuberhealthy
- name: jx-tenant-service
  alias: refresh
  version: 0.0.155
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  condition: refresh.enabled