dependencies:
- name: jxboot-resources
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.14
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx-app-sso
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.14
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jx-app-ui
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.792
